; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
    martinrusk/Stepper MotionControl
    https://github.com/MissouriMRDT/RoveComm_Arduino.git

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git ; Use a community maintained core because the default one is broken
framework = arduino
board_build.core = earlephilhower
board = wiznet_5500_evb_pico
lib_deps = 
    martinrusk/Stepper MotionControl
    https://github.com/Wiznet/Ethernet.git
    https://github.com/MissouriMRDT/RoveComm_Arduino.git
    jrowberg/I2Cdevlib-AK8975

;martinrusk/Stepper MotionControl
